### ISSUE TITLE
Feature argument variants

### ISSUE THREAD

**Issue by perrygeo** [mapbox/cligj#12]
In applying the `@cligj.features_in_arg` [to the mapbox cli](https://github.com/mapbox/mapbox-cli-py/pull/34#issue-122948259), there were a few cases where we needed some slight variants. Specifically, we want to support single-feature arguments, and single/multi-feature options. So
- `@cligj.feature_in_arg` (singular)
- `@cligj.feature_in_opt` 
- `@cligj.features_in_opt`

Naming variants might be nice.

Supporting additional callbacks for user-defined validation functions has also crossed my mind. But I'm leaning towards encouraging that level of validation to go in the processing function itself.

**Do we want a decorator constructor?** something like

```
def features_input(type='arg', name='features', validate_func=None):
    ....
    return decorator
```

**Comment by sgillies** [comment]
For now, we'll stick with multiple features only (single feature being a special case of multiple) and argument only.
