### ISSUE TITLE
Geometry inputs

### ISSUE THREAD

**Issue by perrygeo** [mapbox/cligj#13]
some programs output geojson geometries (not features). See mapshaper as mentioned in https://github.com/perrygeo/python-rasterstats/issues/81 for one such use case

**Question** Do we support a stream of geojson geometries which would be exposed as an iterable of features? Or should the user rely on an external tool (maybe even a job for `jq`?)

**Comment by perrygeo** [comment]
As mentioned elsewhere, jq does the job of taking a stream of geometries and constructing a feautre.

```
fio cat data.shp | jq -c .geometry \
    | jq -c '{"type": "Feature", "properties": {}, "geometry":.}'
```

Is this sufficient? Or is there enough of a need to make `features_in_arg` handle geometries?

/cc @sgillies

**Comment by sgillies** [comment]
@perrygeo handling geometries would simply command line usage considerably. If mapshaper is a significant source of bare geometries, let's do this.
