### ISSUE TITLE
Having trouble reading UTF-8 encoded GeoJSON on Windows

### ISSUE THREAD

**Issue by MrMcFortna** [mapbox/cligj#27]
As documented in [mapbox/tilesets-cli issue #34](https://github.com/mapbox/tilesets-cli/issues/34), cligj does not seem to handle UTF-8 input correctly on Windows. It seems to assume all input is ASCII. The [Get started using Mapbox Tiling Service and the Tilesets CLI](https://docs.mapbox.com/help/tutorials/get-started-mts-and-tilesets-cli/) tutorial uses a UTF-8 file, causing newcomers to immediately hit a hurdle requiring debugging of the libraries used in a tutorial -- not ideal for learning a new process.

The mitigation described in [lorenh's comment on Dec 26, 2019](https://github.com/mapbox/tilesets-cli/issues/34#issuecomment-569142712) seems to make it work for both UTF-8 and ASCII files. Could this solution be incorporated into the cligj project, for the benefit of future developers learning to use the Tilesets CLI?

Thanks!

**Comment by edmangog** [comment]
I have the same problem, cannot even finish the first upload-source step. How can I deal with it? Thanks

**Comment by sgillies** [comment]
@MrMcFortna @edmangog sorry about the slow response. We've got a fix for this in https://pypi.org/project/cligj/0.6b1/#files and I'm pinging the tilesets-cli team to see if they'll help test it. cc @dnomadb 

`pip install cligj==0.6b1` or `pip install -U --pre cligj` to try it out.
