### ISSUE TITLE
Click 8.0 is available

### ISSUE THREAD

**Issue by benoit9126** [mapbox/cligj#37]
Is it possible to modify the dependencies of `cligj` in order to allow the new version of `click`, `click 8.0`? The dependency would become `"click >= 4.0, < 9"`. As long as it is not done here, projects using your library (including projects using `fiona`, `geopandas`, etc with `cligj` as dependencies) won't be able to install click 8.0.

**Comment by benoit9126** [comment]
Thanks a lot!

**Comment by sgillies** [comment]
Since click 8 was compatible with cligj, fiona, and rasterio (except for one weird design choice I made), I removed the cap on click versions. My prediction is that a future click 9 will be compatible as well.

**Comment by benoit9126** [comment]
I will probably do the same for my work. The main features of the library seem to be stable enough for that. Thanks again for your reactivity.
