### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by geowurster** [mapbox/cligj#4]

**Comment by geowurster** [comment]
@sgillies anything else you want to include?

**Comment by geowurster** [comment]
@sgillies any reason not to release this?  I'd like to add plugin support to a module at work.

**Comment by sgillies** [comment]
@geowurster I can get to this today
- [x] Add change log
- [x] tag
- [x] upload to PyPI

**Comment by geowurster** [comment]
Great, thanks!  That will let me start working on the rio and fio changes as well.

**Comment by sgillies** [comment]
@geowurster you rock. Thanks for all your work on this!

**Comment by geowurster** [comment]
Rad.  I'm happy to contribute.
