### ISSUE TITLE
Deprecate plugins functionality in favor of the canonical click-plugins repo

### ISSUE THREAD

**Issue by geowurster** [mapbox/cligj#6]
@sgillies How do you feel about deprecating `cligj.plugins` in favor of [click-plugins](https://github.com/click-contrib/click-plugins)?  If you're :+1: I'll submit a PR here and open issues in Fiona and rasterio.

The code is largely unchanged, although there is a slight modification to the API:

``` pythion
import click
from click_plugins import with_plugins

@with_plugins(iter_entry_points('entry.point')
@click.group()
def cli():
    """Some CLI"""

@cli.command()
def subcommand():
    """I do something"""
```

**Comment by sgillies** [comment]
Sure. Might be a good catalyst for a 1.0 as well.
